# fly.toml app configuration file generated for full-stack-open-pokedex-restless-voice-3470 on 2024-12-29T07:53:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-restless-voice-3470'
primary_region = 'arn'

[build]

[deploy]
  strategy = 'canary'

[env]
  PORT = '3000'

[processes]
  app = 'node app.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '86400s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
