name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    outputs:
      skip_deploy: ${{ steps.check_skip.outputs.skip_deploy }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e test
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Check for #skip in commit messages
        id: check_skip
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          messages="${{ join(github.event.commits.*.message, ' ') }}"
          if echo "$messages" | grep -q "#skip"; then
            echo "skip_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "skip_deploy=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-latest
    concurrency: deploy-group
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.simple_deployment_pipeline.outputs.skip_deploy != 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Notify Discord of Successful Deployment
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: |
            🚀 **Deployment Successful!**
            **Version:** ${{ needs.tag_release.outputs.new_tag }}
            **Commit:** [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          username: "GitHub Actions"
          avatarUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

  tag_release:
    needs: deploy
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.simple_deployment_pipeline.outputs.skip_deploy != 'true' }}
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: false

  notify_failure:
    if: failure()
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Get Last Commit Message
        id: last_commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
      - name: Notify Discord of Failure
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          details: |
            💥 **Build Failed!**
            **Commit:** [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            **Message:** ${{ steps.last_commit.outputs.message }}
            **Job:** ${{ github.job }}
            Please check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
          username: "GitHub Actions"
          avatarUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
